server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Fallback to index.html for Single Page Applications
        try_files $uri $uri/ /index.html;
    }
}
